### ISSUE TITLE
:action remaps that open a new window/input don't work

### ISSUE THREAD

**Issue by prurph** [saaguero/ideavimrc#1]
Awesome settings, thanks! I'm running into some issues with some of the `:action` mappings though. Do they still work for you?

On IntelliJ Community Edition 2016.1.3, `nnoremap / :action Find<CR>` opens the system find dialog/input, but the editor window is immediately focused so you can't actually type into it. I run into the same issue with stuff like `GotoFile` and `GotoClass` as well. Is this something I'm doing wrong or did something in IdeaVIM break along the way that these no longer function properly?

**Comment by saaguero** [comment]
Hey!

I'm having the same problem under Linux. In Windows it works correctly.

It might be related to ideavim, take a look at:
https://youtrack.jetbrains.com/issue/VIM-796

I recommend to create a bug in ideavim project.

**Comment by prurph** [comment]
Wow, thank you! I was digging through the ideavim issues but didn't find that particular one you linked. It led me to: https://teamcity.jetbrains.com/viewType.html?buildTypeId=IdeaVim_Build&guest=1 where I was able to download the latest CI build and install it (Plugins > Install From Disk) and now it works on OS X!

This really makes my day, thank you!

**Comment by saaguero** [comment]
Glad I could help. All credit goes to ideavim's awesome people!
